In [11]:
import array as arr
import numpy as np

a=[1,6,8]
a=arr.array('b',a)
n=a*2
print(n)

a1=np.array(a)
n1=a1*2
print(n1)

array('b', [1, 6, 8, 1, 6, 8])
[ 2 12 16]


In [17]:
import numpy as np
x=np.zeros([5,5])
y=np.ones([5,5])
print(x)
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import cv2
img=cv2.imread("windows.jpg",0)
cv2